### ISSUE TITLE
overly verbose default logging

### ISSUE THREAD

**Issue by set135** [khenriks/mp3fs#50] opened 2017-03-16 09:05 UTC
the 'debug' option only makes mp3fs echo its verbose logs to stderr. It still spams syslog with debug output. (nearly 7megs just playing one album) I fixed it by modifying my syslogger settings, but you might want to consider not logging debug messages by default. Or having a log-level threshhold. Heck just having a #define mp3fs_debug to do nothing by default would fix most of it, since no actual user is interested in that.

**Comment by khenriks** [comment] 2017-04-22 03:08
This is a duplicate of #10.

**Closed by khenriks** 2017-04-22 03:08 UTC
